const { version, version } = require("react")

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
        - name: checkout code 
        uses: actions/checkout@v3

        - name: Use Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '18'

        - name: lnstall dependencies
         run: npm install

         - name: build
         run: npm run build
